rails-forms-and-validations/bagel_store/config/routes.rb
Rails.application.routes.draw do
  resources :bagels
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-forms-and-validations/bagel_store/app/models/bagel.rb
class Bagel < ApplicationRecord
  validates :name, :price, presence: true 
  validates :name, uniqueness: true
  validate :validate_num_for_price

  def validate_num_for_price
    if self.price.class != Float || self.price > 30
      self.errors.add(:price, "Needs to be a number less than 30")
    end
  end
end

rails-forms-and-validations/bagel_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-forms-and-validations/bagel_store/app/controllers/bagels_controller.rb
class BagelsController < ApplicationController
  before_action :set_bagel, only: [:show, :edit, :update, :destroy]

  # GET /bagels
  # GET /bagels.json
  def index
    @bagels = Bagel.all
  end

  # GET /bagels/1
  # GET /bagels/1.json
  def show
  end

  # GET /bagels/new
  def new
    @bagel = Bagel.new
  end

  # GET /bagels/1/edit
  def edit
  end

  # POST /bagels
  # POST /bagels.json
  def create
    @bagel = Bagel.new(bagel_params)

    if @bagel.save
      redirect_to bagel_path(@bagel)
    else
      render :new
    end
  end

  # PATCH/PUT /bagels/1
  # PATCH/PUT /bagels/1.json
  def update
    respond_to do |format|
      if @bagel.update(bagel_params)
        format.html { redirect_to @bagel, notice: 'Bagel was successfully updated.' }
        format.json { render :show, status: :ok, location: @bagel }
      else
        format.html { render :edit }
        format.json { render json: @bagel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bagels/1
  # DELETE /bagels/1.json
  def destroy
    @bagel.destroy
    respond_to do |format|
      format.html { redirect_to bagels_url, notice: 'Bagel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagel
      @bagel = Bagel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bagel_params
      params.require(:bagel).permit(:name, :price, :tasty)
    end
end

rails-forms-and-validations/bagel_store/app/helpers/bagels_helper.rb
module BagelsHelper
end

rails-forms-and-validations/bagel_store/app/views/bagels/_form.html.erb
<%= form_with(model: bagel, local: true) do |form| %>

  <% if bagel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bagel.errors.count, "error") %> prohibited this bagel from being saved:</h2>

      <ul>
        <% bagel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%# <%= form.text_field :price %>
    <%= number_field(:bagel, :price, in: 0.5..30.0, step: 0.05 ) %>
  </div>

  <div class="field">
    <%= form.label :tasty %>
    <%= form.check_box :tasty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-forms-and-validations/bagel_store/app/views/bagels/edit.html.erb
<h1>Editing Bagel</h1>

<%= render 'form', bagel: @bagel %>

<%= link_to 'Show', @bagel %> |
<%= link_to 'Back', bagels_path %>

rails-forms-and-validations/bagel_store/app/views/bagels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bagels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Tasty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bagels.each do |bagel| %>
      <tr>
        <td><%= bagel.name %></td>
        <td><%= bagel.price %></td>
        <td><%= bagel.tasty %></td>
        <td><%= link_to 'Show', bagel %></td>
        <td><%= link_to 'Edit', edit_bagel_path(bagel) %></td>
        <td><%= link_to 'Destroy', bagel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bagel', new_bagel_path %>

rails-forms-and-validations/bagel_store/app/views/bagels/new.html.erb
<h1>New Bagel</h1>

<%= render 'form', bagel: @bagel %>

<%= link_to 'Back', bagels_path %>

rails-forms-and-validations/bagel_store/app/views/bagels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bagel.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bagel.price %>
</p>

<p>
  <strong>Tasty:</strong>
  <%= @bagel.tasty %>
</p>

<%= link_to 'Edit', edit_bagel_path(@bagel) %> |
<%= link_to 'Back', bagels_path %>

rails-forms-and-validations/bagel_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BagelStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>